### PR TITLE
Clean content file from useless logs

### PR DESCRIPTION
**Pull request by raouf-elmeddah**
removed useless console.log :)

### CODE REVIEW

**Comment by raouf-elmeddah** [comment]
too much consol logging

**Comment by AmitBokoDev** [comment]
Well you could look at it like this- they are all useless, sure, until something breaks. This is still very much a beta, if something doesn't work properly I would like logs from the users, and it doesn't affect performance almost at all.

tl;dr - Will be removed in the future, not yet.

**Comment by gopaljigaur** [comment]
Some of the logs could be downgraded to `debug` to reduce the amount of info logging.

**Comment by raouf-elmeddah** [comment]
for now i'm working on the styling but its late & i cant focus the way i want.
please check the style i'm currently at & i'll try to push a commit tomorrow ( i hope, still having conflict with main js part & the counter).
[https://i.imgur.com/om0P9d8.png](https://i.imgur.com/om0P9d8.png)(current styling state)

**Comment by AmitBokoDev** [comment]
Looks alright, the +- on the days counter looks kinda redundant to me since
you are most likely to enter a number manually and not go up or down. For
that I'll add a 'quality of life' piece of code that just marks the whole
text when you click on it.
Also, if you're working on the style then make it dark mode from the get
go, I didn't change it to black just cuz I was lazy.
About the JS there was a small bug that I fixed, so try to pull the latest
code.
Anyway, it looks great, thanks for contributing!

‫בתאריך יום א׳, 12 בפבר׳ 2023 ב-1:52 מאת ‪AYASOFT.NET‬‏ <‪
***@***.***‬‏>:‬

**Comment by AmitBokoDev** [comment]
Also also, make it fit mobile if you can! It was just approved for Firefox,
and the firefox app supports mobile, which means we gonna have the filter
on mobile!
But, it looks bad on mobile, the popup is treated as a whole page, and it
doesn't scale up (see pic attached).
So if you don't mind, try to make it fit mobile, you can test it by opening
index.html on its own and selecting mobile view in the debug window, I'm
sure you know how.

Thanks again!

‫בתאריך יום א׳, 12 בפבר׳ 2023 ב-2:15 מאת ‪Amit Bokobza‬‏ <‪
***@***.***‬‏>:‬

**Comment by raouf-elmeddah** [comment]
just commited some styling change in my fork ,
it's only the begining , i'm puting  a layout for the pop up & diffirent options .
full time job doesn't allow much time for coding

**Pull request closed without merging**
